version: '3.8'

services:
  tg-pansou-bot:
    build: .
    container_name: tg-pansou-bot
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    # 使用 host 网络模式
    network_mode: host
